import requests
import json
import sys

BASE_URL = "http://localhost:8000"

def test_incident_reporter():
    print(f"\n--- Testing Incident Reporter ({BASE_URL}/incident/analyze) ---")
    payload = {
        "text": "Yesterday night around 10 PM, I was walking home when a man on a motorbike snatched my gold chain and sped away. I fell down and got hurt on my knees.",
        "language": "en"
    }
    
    try:
        response = requests.post(f"{BASE_URL}/incident/analyze", json=payload, timeout=120)
        if response.status_code == 200:
            data = response.json()
            fir_text = data.get("fir_text", "")
            print("✓ Request Successful")
            print(f"FIR Length: {len(fir_text)} chars")
            
            if "(Generated by Local AI via Ollama)" in fir_text:
                print("✓ OLLAMA ACTIVE: FIR generated by AI!")
            elif "(Template Mode)" in fir_text:
                print("⚠ OLLAMA INACTIVE: FIR generated by Template.")
            else:
                print("? Unknown generation mode.")
                
            print("\nPreview:")
            print(fir_text[:500] + "...")
        else:
            print(f"✗ Failed: {response.status_code} - {response.text}")
    except Exception as e:
        print(f"✗ Error: {e}")

def test_chat_assistant():
    print(f"\n--- Testing Chat Assistant ({BASE_URL}/chat/) ---")
    payload = {
        "message": "What is the punishment for theft under IPC?"
    }
    
    try:
        response = requests.post(f"{BASE_URL}/chat/", json=payload, timeout=120)
        if response.status_code == 200:
            data = response.json()
            reply = data.get("reply", "")
            print("✓ Request Successful")
            print(f"Reply Length: {len(reply)} chars")
            
            if "(Answered by Local AI via Ollama)" in reply:
                print("✓ OLLAMA ACTIVE: Answered by AI!")
            else:
                print("⚠ OLLAMA INACTIVE or Fallback used.")
                
            print("\nPreview:")
            print(reply[:500] + "...")
        else:
            print(f"✗ Failed: {response.status_code} - {response.text}")
    except Exception as e:
        print(f"✗ Error: {e}")

if __name__ == "__main__":
    print("Starting End-to-End Tests...")
    test_incident_reporter()
    test_chat_assistant()
